version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: my-nginx
    ports:
      - "80:80"
    volumes:
      - ./html/index.html:/usr/share/nginx/html/index.html
    restart: unless-stopped